.PHONY: help build check run
.DEFAULT_GOAL := help

BIN_NAME := x

# cargo build
build:
	@cargo build

# cargo check
check:
	@cargo check

# clean cargo cache
clean:
	@cargo clean

# cargo build --release
release:
	@cargo build --release

# cargo run
run:
	@cargo run

# run binary generated by cargo build
run-bin:
	@./target/debug/$(BIN_NAME)


# Show help
help:
	@echo ""
	@echo "Usage:"
	@echo "    make [target]"
	@echo ""
	@echo "Targets:"
	@awk '/^[a-zA-Z\-_0-9]+:/ \
	{ \
		helpMessage = match(lastLine, /^# (.*)/); \
		if (helpMessage) { \
			helpCommand = substr($$1, 0, index($$1, ":")-1); \
			helpMessage = substr(lastLine, RSTART + 2, RLENGTH); \
			printf "\033[36m%-22s\033[0m %s\n", helpCommand,helpMessage; \
		} \
	} { lastLine = $$0 }' $(MAKEFILE_LIST)
